---
openapi: 3.0.3
info:
  title: OneCx IAM Bff
  version: 1.0.0
servers:
  - url: "http://onecx-iam-bff:8080"
tags:
  - name: UsersInternal
    description: Keycloak user internal service
paths:
  /users/search:
    post:
      x-onecx:
        permissions:
          user:
            - read
      tags:
        - UsersInternal
      summary: Search users by criteria
      operationId: searchUsersByCriteria
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSearchCriteria'
      responses:
        200:
          description: OK
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/UserPageResult"
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
  /users/password:
    put:
      x-onecx:
        permissions:
          user:
            - write
      tags:
        - UsersInternal
      summary: Reset user password
      operationId: resetPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserResetPasswordRequest'
      responses:
        204:
          description: Reset password succeeded
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
  /roles/search:
    post:
      x-onecx:
        permissions:
          role:
            - read
      tags:
        - RolesInternal
      summary: Search roles by criteria
      operationId: searchRolesByCriteria
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoleSearchCriteria'
      responses:
        200:
          description: OK
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/RolePageResult"
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
  /roles/{userId}:
    get:
      x-onecx:
        permissions:
          role:
            - read
      tags:
        - RolesInternal
      summary: Get roles of user by id
      operationId: getUserRoles
      parameters:
        - name: userId
          in: path
          required: true
          description: Keycloak userId
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            "application/json":
              schema:
                $ref: '#/components/schemas/UserRolesResponse'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
components:
  schemas:
    UserRolesResponse:
      type: object
      properties:
        roles:
          type: array
          items:
            $ref: '#/components/schemas/Role'
    UserSearchCriteria:
      type: object
      properties:
        userName:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        pageNumber:
          format: int32
          description: The number of page.
          default: 0
          type: integer
        pageSize:
          format: int32
          description: The size of page
          default: 100
          maximum: 1000
          type: integer
    UserPageResult:
      type: object
      properties:
        totalElements:
          format: int64
          description: The total elements in the resource.
          type: integer
        number:
          format: int32
          type: integer
        size:
          format: int32
          type: integer
        totalPages:
          format: int64
          type: integer
        stream:
          type: array
          items:
            $ref: '#/components/schemas/User'
    User:
      type: object
      properties:
        id:
          type: string
        origin:
          type: string
        createdTimestamp:
          $ref: '#/components/schemas/OffsetDateTime'
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        attributes:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
    ProblemDetailResponse:
      type: object
      properties:
        errorCode:
          type: string
        detail:
          type: string
        params:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailParam'
        invalidParams:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailInvalidParam'
    UserResetPasswordRequest:
      type: object
      required:
        - password
      properties:
        password:
          type: string
          format: password
          minLength: 1
    RoleSearchCriteria:
      type: object
      properties:
        name:
          type: string
        pageNumber:
          format: int32
          description: The number of page.
          default: 0
          type: integer
        pageSize:
          format: int32
          description: The size of page
          default: 100
          maximum: 1000
          type: integer
    RolePageResult:
      type: object
      properties:
        totalElements:
          format: int64
          description: The total elements in the resource.
          type: integer
        number:
          format: int32
          type: integer
        size:
          format: int32
          type: integer
        totalPages:
          format: int64
          type: integer
        stream:
          type: array
          items:
            $ref: '#/components/schemas/Role'
    Role:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
    ProblemDetailParam:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    ProblemDetailInvalidParam:
      type: object
      properties:
        name:
          type: string
        message:
          type: string
    OffsetDateTime:
      format: date-time
      type: string
      example: 2022-03-10T12:15:50-04:00